version: '3'

networks:
  app_network:
    driver: bridge

services:
  app: 
    build: .
    container_name: app
    image: node:latest
    env_file:
      - .env
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_HOST=172.17.0.1
    networks:
      - app_network
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: "bash -c 'npm install && npm run start:dev'"
    depends_on:
      - db

  db:
    container_name: database
    image: postgres
    env_file:
      - .env
    networks:
      - app_network
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
